init fix

diff --git a/init/archeyjs b/init/archeyjs
--- a/init/archeyjs
+++ b/init/archeyjs
@@ -42,11 +42,11 @@ run_by_init() {
     ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
 }
 
-check_for_upstart() {
-    if init_is_upstart; then
-	exit $1
-    fi
-}
+# check_for_upstart() {
+#     if init_is_upstart; then
+# 	exit $1
+#     fi
+# }
 
 # check_for_no_start() {
 #     # forget it if we're trying to start, and /etc/ssh/sshd_not_to_be_run exists
@@ -91,7 +91,7 @@ export PATH="${PATH:+$PATH:}/usr/local/bin"
 
 case "$1" in
   start)
-	check_for_upstart 1
+# 	check_for_upstart 1
 # 	check_privsep_dir
 # 	check_for_no_start
 # 	check_dev_null
@@ -103,7 +103,7 @@ case "$1" in
 	fi
 	;;
   stop)
-	check_for_upstart 0
+# 	check_for_upstart 0
 	log_daemon_msg "Stopping archeyjs server" "archeyjs" || true
 	if start-stop-daemon --stop --quiet --oknodo --pidfile $PID; then
 	    log_end_msg 0 || true
@@ -125,7 +125,7 @@ case "$1" in
 # 	;;
 
   restart)
-	check_for_upstart 1
+# 	check_for_upstart 1
 # 	check_privsep_dir
 # 	check_config
 	log_daemon_msg "Restarting archeyjs server" "archeyjs" || true
@@ -139,39 +139,39 @@ case "$1" in
 	fi
 	;;
 
-  try-restart)
-	check_for_upstart 1
-# 	check_privsep_dir
-# 	check_config
-	log_daemon_msg "Restarting archeyjs server" "archeyjs" || true
-	RET=0
-	start-stop-daemon --stop --quiet --retry 30 --pidfile $PID || RET="$?"
-	case $RET in
-	    0)
-		# old daemon stopped
-# 		check_for_no_start log_end_msg
-# 		check_dev_null log_end_msg
-		if start-stop-daemon --start --quiet --oknodo --pidfile $PID --exec $DAEMON -- $ARGS; then
-		    log_end_msg 0 || true
-		else
-		    log_end_msg 1 || true
-		fi
-		;;
-	    1)
-		# daemon not running
-		log_progress_msg "(not running)" || true
-		log_end_msg 0 || true
-		;;
-	    *)
-		# failed to stop
-		log_progress_msg "(failed to stop)" || true
-		log_end_msg 1 || true
-		;;
-	esac
+#   try-restart)
+# 	check_for_upstart 1
+# # 	check_privsep_dir
+# # 	check_config
+# 	log_daemon_msg "Restarting archeyjs server" "archeyjs" || true
+# 	RET=0
+# 	start-stop-daemon --stop --quiet --retry 30 --pidfile $PID || RET="$?"
+# 	case $RET in
+# 	    0)
+# 		# old daemon stopped
+# # 		check_for_no_start log_end_msg
+# # 		check_dev_null log_end_msg
+# 		if start-stop-daemon --start --quiet --oknodo --pidfile $PID --exec $DAEMON -- $ARGS; then
+# 		    log_end_msg 0 || true
+# 		else
+# 		    log_end_msg 1 || true
+# 		fi
+# 		;;
+# 	    1)
+# 		# daemon not running
+# 		log_progress_msg "(not running)" || true
+# 		log_end_msg 0 || true
+# 		;;
+# 	    *)
+# 		# failed to stop
+# 		log_progress_msg "(failed to stop)" || true
+# 		log_end_msg 1 || true
+# 		;;
+# 	esac
 	;;
 
   status)
-	check_for_upstart 1
+# 	check_for_upstart 1
 	status_of_proc -p $PID $DAEMON archeyjs && exit 0 || exit $?
 	;;
 
